### ISSUE TITLE
Regex help

### ISSUE THREAD

**Issue by okaku** [wltb/ff_feedcleaner#2]
Hi wltb-san.

Can you help me with regex for a feed to which I would like to append something?

**Feed-URL:** http://www.faz.net/aktuell/feuilleton/?rssview=1
Example of **article URL** (that is sent to browser): http://www.faz.net/-gs6-8df7v

I would like to append this to the article URL:    **?printPagedArticle=true**
So final link should look like this:  http://www.faz.net/-gs6-8df7v?printPagedArticle=true

I've tried variations of this but none works:

        "URL": "www.faz.net",
        "type": "xpath_regex",
        "xpath": "//item/link",
        "pattern": "#$#",
        "replacement": "?printPagedArticle=true"

Thank you very much for your help.

**Comment by wltb** [comment]
Your regex looks fine (although I didn't test it), but you are barking up the wrong xpath - try "//item/guid" instead. Note that on the very first fetch, each article in the feed will be reimported since this changes the guid.

This happens because ttrss prefers the guid entry over the link entry if isPermaLink is set to true in the former. When I have some time on my hands, I'll implement a type that makes manipulations like this easier to accomplish.

**Comment by wltb** [comment]
Implemented the new type and used your example in the docs.
